name: now_shipping
description: A shipping management application.
publish_to: 'none'
version: 1.0.7+8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.1
  go_router: ^16.2.4
  http: ^1.1.2
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  riverpod: ^3.0.1
  hooks_riverpod: ^3.0.1
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  lottie: ^3.0.0
  svg_flutter: ^0.0.1
  shimmer: ^3.0.0
  mobile_scanner: ^7.1.2
  flutter_plugin_android_lifecycle: ^2.0.19
  path_provider: ^2.1.5
  google_maps_flutter: ^2.5.3
  geocoding: ^4.0.0
  geolocator: ^13.0.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.1
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.2.4
  flutter_spinkit: ^5.2.1
  open_file: ^3.5.10
  riverpod_lint: ^3.0.1
  permission_handler: ^11.3.1
  share_plus: ^7.2.2
  
  # Firebase
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.5
  
  # Local Notifications
  flutter_local_notifications: ^18.0.1
  
  # Time formatting
  timeago: ^3.7.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#f29620"
  adaptive_icon_foreground: "assets/icons/icon_only_white.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/regions/
